number=int(input("enter preferred number")
print(number*1)
print(number*2)
print(number*3)
print(number*4)
print(number*5)           
print(number*5) 
print(number*5) 
print(number*5) 
print(number*5) 
print(number*5) 
print(number*5) 
